name: Deploy Informe Interactivo

on:
  schedule:
    - cron: '15 7 * * FRI'      # Verano (07:15 UTC -> 09:15 Madrid)
    - cron: '15 8 * * FRI'      # Invierno (08:15 UTC -> 09:15 Madrid)
  workflow_dispatch:          # Permite ejecutarlo manualmente también

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy openpyxl plotly requests fuzzywuzzy python-Levenshtein statsmodels geopandas
          sudo apt-get update
          sudo apt-get install -y libspatialindex-dev
          
      - name: Generar informe interactivo
        env:
          OUTPUT_FOLDER: output_html
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          IDEALISTA_API_KEY: ${{ secrets.IDEALISTA_API_KEY }}
          IDEALISTA_SECRET: ${{ secrets.IDEALISTA_SECRET }}
        run: |
          python informe_semanal.py

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'output_html'
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
