name: Procesar Leads de Idealista

on:
  # Ejecuta el flujo cada 5 minutos
  schedule:
    - cron: '*/5 * * * *'
  # Permite ejecutarlo manualmente desde la pestaña Actions para pruebas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script para procesar correos
        run: node process-emails.js
        env:
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_ID: ${{ secrets.AIRTABLE_TABLE_ID }}
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          OUTLOOK_CLIENT_ID: ${{ secrets.OUTLOOK_CLIENT_ID }}
          OUTLOOK_CLIENT_SECRET: ${{ secrets.OUTLOOK_CLIENT_SECRET }}
          OUTLOOK_TENANT_ID: ${{ secrets.OUTLOOK_TENANT_ID }}
          OUTLOOK_USER_EMAIL: ${{ secrets.OUTLOOK_USER_EMAIL }}
