name: Ejecutar Script Idealista

on:
  schedule:
    - cron: '0 9 * * FRI'  # Todos los viernes a las 9:00 AM UTC
  workflow_dispatch:       # Permite ejecutar manualmente también

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas numpy fuzzywuzzy openpyxl python-Levenshtein

      - name: Ejecutar script
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          IDEALISTA_API_KEY: ${{ secrets.IDEALISTA_API_KEY }}
          IDEALISTA_SECRET: ${{ secrets.IDEALISTA_SECRET }}
        run: python api_idealista.py
